version: '3.8'

services:
  aplicacao:
   image: aplicacao
   privileged: true
   user: root
   ports:
    - 8000:8000
   container_name: container_aplicacao
   volumes:
     - ./:/app
     - /var/run/docker.sock:/var/run/docker.sock
